service:
  name: api-tickets

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs6.10
  region: ap-northeast-2
  memorySize: 128
  environment: ${file(./env.yml):${self:provider.stage}}

functions:
  githubAuthenticator:
    handler: functions/authenticator/handler.github
    description: "github authenticator"
    events:
      - http:
          method: get
          path: /auth/github
